### ISSUE TITLE
Не устанавливается на Windows

### ISSUE THREAD

**Issue by barakuda211** [aromansky/SmartStudy#9]
Сертификат установлен, но установщик всё равно на него ругается. Текст ошибки прилагаю:

Не удалось проверить сертификат издателя этого пакета приложения. Обратитесь к системному администратору или разработчику приложения, чтобы получить новый сертификат с проверенными сертификатами. Корневой сертификат и все непосредственные сертификаты подписи в пакете приложения должны быть проверены (0x800B010A)

**Comment by aromansky** [comment]
[Здесь](https://drive.google.com/drive/u/0/folders/106N5f2ts7B7Q3euw5qK4qR9XaERoKpSn) находится обновлённый алгоритм установки
